name: document_opener
description: A Flutter package to open PDF and CSV files without requesting broad media permissions.
version: 1.0.3
homepage: https://github.com/julien-kv/document_opener

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.scanpay.document_opener
        pluginClass: DocumentOpenerPlugin
      ios:
        pluginClass: DocumentOpenerPlugin
